import matplotlib.font_manager as fm

FONT_PATH = 'assets/fonts/Roboto_Mono/RobotoMono-VariableFont_wght.ttf'
ITALIC_FONT_PATH = 'assets/fonts/Roboto_Mono/RobotoMono-Italic-VariableFont_wght.ttf'
ROBOTO = fm.FontProperties(fname=FONT_PATH)
ITALIC_ROBOTO = fm.FontProperties(fname=ITALIC_FONT_PATH)

INSTRUMENT_SERIF_PATH = 'assets/fonts/Instrument_Serif/InstrumentSerif-Regular.ttf'
INSTRUMENT_SERIF_ITALIC_PATH = 'assets/fonts/Instrument_Serif/InstrumentSerif-Italic.ttf'
INSTRUMENT_SERIF = fm.FontProperties(fname=INSTRUMENT_SERIF_PATH)
INSTRUMENT_SERIF_ITALIC = fm.FontProperties(fname=INSTRUMENT_SERIF_ITALIC_PATH)

TEAM_COLORS = {
    "Air Force": "#0033A0",
    "Akron": "#041E42",
    "Alabama": "#9E1B32",
    "Alabama A&M":"#660000",
    "App State": "#FFCC00",
    "Arizona": "#CC0033",
    "Arizona State": "#8C1D40",
    "Arkansas": "#9D2235",
    "Arkansas State": "#CC092F",
    "Army": "#BFAF80",
    "Auburn": "#0C2340",
    "Ball State": "#BA0C2F",
    "Baylor": "#154733",
    "Boise State": "#0033A0",
    "Boston College": "#98002E",
    "Bowling Green": "#FE5000",
    "Brown":"#4E3629",
    "BYU": "#002E5D",
    "Buffalo": "#005BBB",
    "California": "#003262",
    "Central Arkansas":"#4F2D7F",
    "Central Michigan": "#6A0032",
    "Charlotte": "#154734",
    "Cincinnati": "#D50032",
    "Clemson": "#F56600",
    "Coastal Carolina": "#007C92",
    "Colorado": "#CFB87C",
    "Colorado State": "#2A6833",
    "Columbia":"#003865",
    "Cornell":"#B31B1B",
    "Dartmouth":"#046A38",
    "Delaware":"#00539f",
    "Duke": "#00539B",
    "East Carolina": "#592A8A",
    "Eastern Michigan": "#006633",
    "Eastern Washington":"#A10022",
    "Florida": "#0021A5",
    "Florida A&M": "#EE7624",
    "Florida Atlantic": "#002855",
    "Florida International": "#081E3F",
    "Florida State": "#782F40",
    "Fresno State": "#D50032",
    "Georgia": "#BA0C2F",
    "Georgia Southern": "#041E42",
    "Georgia Tech": "#B3A369",
    "Georgia State": "#0033A0",
    "Harvard":"#QA41034",
    "Hawai'i": "#024731",
    "Holy Cross":"#602D89",
    "Houston": "#C8102E",
    "Idaho": "#B3995D",
    "Idaho State":"#FF671F",
    "Illinois": "#E84A27",
    "Indiana": "#990000",
    "Iowa": "#FFCD00",
    "Iowa State": "#C8102E",
    "James Madison": "#450084",
    "Jacksonville State": "#A30D26",
    "Kansas": "#0051BA",
    "Kansas State": "#512888",
    "Kennesaw State": "#FFCC00",
    "Kent State": "#FDC82F",
    "Kentucky": "#0033A0",
    "Lenoir-Rhyne":"#810027",
    "Louisiana": "#D50032",
    "Louisiana Tech": "#0046AD",
    "Liberty": "#A6192E",
    "Louisville": "#AD0000",
    "LSU": "#461D7C",
    "Marshall": "#00A862",
    "Maryland": "#E03A3E",
    "Memphis": "#003087",
    "Miami": "#005030",
    "Miami (OH)": "#BA0C2F",
    "Michigan": "#00274C",
    "Michigan State": "#18453B",
    "Middle Tennessee": "#005DAA",
    "Minnesota": "#7A0019",
    "Missouri": "#F1B82D",
    "Mississippi State": "#660000",
    "Montana":"#660033",
    "Montana State":"#00205B",
    "Navy": "#00205B",
    "North Carolina State": "#CC0000",
    "NC State": "#CC0000",
    "Nebraska": "#D00000",
    "Nevada": "#003366",
    "North Carolina": "#4B9CD3",
    "North Carolina A&T":"#F3B237",
    "New Mexico": "#D50032",
    "New Mexico State": "#862633",
    "North Dakota State":"#0A5640",
    "Northern Colorado":"#013C65",
    "Northern Arizona":"#003466",
    "Northern Illinois": "#C8102E",
    "North Texas": "#00853E",
    "Northwestern": "#4E2A84",
    "Notre Dame": "#C99700",
    "Ohio": "#006A4D",
    "Ohio State": "#BB0000",
    "Oklahoma": "#841617",
    "Oklahoma State": "#FF7300",
    "Old Dominion": "#041E42",
    "Ole Miss": "#CE1126",
    "Oregon": "#154733",
    "Oregon State": "#DC4405",
    "Penn":"#011F5B",
    "Penn State": "#041E42",
    "Portland State":"#154734",
    "Pittsburgh": "#003594",
    "Princeton":"#FF671F",
    "Purdue": "#C28E0E",
    "Rice": "#00205B",
    "Rutgers": "#CC0033",
    "Sacramento State":"#043927",
    "Sam Houston": "#E35205",
    "San Diego State": "#A6192E",
    "San José State": "#0055A2",
    "SMU": "#C60C30",
    "South Alabama": "#041E42",
    "South Carolina": "#73000A",
    "South Florida": "#006747",
    "Southern Miss": "#FFC72C",
    "Southern Utah":"#C41425",
    "Stanford": "#8C1515",
    "Texas State": "#461D7C",
    "Syracuse": "#D44500",
    "TCU": "#4D1979",
    "Temple": "#9E1B32",
    "Tennessee": "#FF8200",
    "Texas": "#BF5700",
    "Texas A&M": "#500000",
    "Texas Tech": "#C8102E",
    "Toledo": "#15397F",
    "Troy": "#841617",
    "Tulane": "#008E97",
    "Tulsa": "#007AC1",
    "UAB": "#006A4D",
    "UCF": "#ba9b37",
    "UCLA": "#2774AE",
    "UConn": "#041E42",
    "UL Monroe": "#862633",
    "UMass": "#881C1C",
    "UNLV": "#BA0C2F",
    "USC": "#9D2235",
    "Southern California": "#9D2235",
    "Utah": "#CC0000",
    "Utah State": "#041E42",
    "UTEP": "#041E42",
    "UTSA": "#0C2340",
    "Vanderbilt": "#866D4B",
    "Villanova":"#00205B",
    "Virginia Tech": "#630031",
    "Virginia": "#232D4B",
    "Wake Forest": "#9E7E38",
    "Washington": "#4B2E83",
    "Washington State": "#981E32",
    "Weber State":"#4B2682",
    "Western Kentucky": "#D50032",
    "Western Michigan": "#5A3825",
    "West Virginia": "#EAAA00",
    "Wyoming": "#FFC72C",
    "William & Mary": "#115740",
    "Wisconsin": "#C5050C",
    "Yale":"#00356B",
}

EXCLUDE_FROM_KNN = {
    "QB": ["comp_att"],
    "TE": ["Bench Press", "3Cone","Shuttle","fumbles_fum","Fumbles"],
    "LB": ["defensive_td", "interceptions_td", "interceptions_yds", "interceptions_avg"],
    "DE/LB": ["defensive_td", "interceptions_td", "interceptions_yds", "interceptions_avg"],
    "DB": ["interceptions_td", "interceptions_avg", "defensive_td"],
    "DL": ["defensive_td", "interceptions_td", "interceptions_yds", "interceptions_avg"],
    "DT": ["defensive_td", "interceptions_td", "interceptions_yds", "interceptions_avg"]
}

POSITION_BASELINES = {
    "QB": [
        "ppa_per_dropback", "comp_att", "passing_pct", "passing_yds", "passing_td",
        "passing_ypa", "passing_int", "rushing_car", "rushing_yds",
        "rushing_td", "fumbles_fum"
    ],
    "RB": [
        "rushing_car", "rushing_yds", "rushing_td", "rushing_ypc",
        "receiving_rec", "receiving_yds", "receiving_td", "fumbles_fum"
    ],
    "WR": [
        "receiving_rec", "receiving_yds", "receiving_td",
        "epa_per_rec", "receiving_ypr", "fumbles_fum"
    ],
    "TE": [
        "receiving_rec", "receiving_yds", "receiving_td",
        "receiving_ypr", "fumbles_fum"
    ],
    "CB": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "interceptions_int",
        "interceptions_yds", "interceptions_avg", "interceptions_td",
        "defensive_pd", "defensive_td"
    ],
    "DB": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "interceptions_int",
        "interceptions_yds", "interceptions_avg", "interceptions_td",
        "defensive_pd", "defensive_td"
    ],
    "DE": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "defensive_sacks", "defensive_qb_hur", "Height (in)"
    ],
    "DT": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "defensive_sacks", "defensive_qb_hur"
    ],
    "DL": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "defensive_sacks", "defensive_qb_hur"
    ],
    "DE/LB": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "defensive_sacks",
        "defensive_qb_hur", "Height (in)", "interceptions_int",
        "interceptions_yds", "interceptions_avg", "interceptions_td",
        "defensive_pd", "defensive_td"
    ],
    "LB": [
        "defensive_solo", "defensive_tot", "defensive_tfl", "defensive_sacks", "defensive_qb_hur", "interceptions_int",
        "interceptions_yds", "interceptions_avg", "interceptions_td",
        "defensive_pd", "defensive_td"
    ],
        "K": [
      "kicking_fgm","kicking_fga","kicking_pct","kicking_xpa","kicking_xpm","kicking_pts"
    ],
        "P": [
      "punting_no","punting_yds","punting_in_20","punting_tb"
    ],
        "OL": []
}

COLUMN_RENAME_MAP = {
    "ppa_per_dropback": "EPA/Dropback",
    "comp_att": "Comp/Att",
    "passing_att": "Attempts",
    "passing_completions": "Completions",
    "passing_pct": "Completion %",
    "passing_yds": "Passing Yards",
    "passing_td": "Passing TDs",
    "passing_ypa": "Yards per Attempt",
    "passing_int": "Interceptions",
    "rushing_car": "Rush Attempts",
    "rushing_yds": "Rushing Yards",
    "rushing_td": "Rushing TDs",
    "rushing_ypc": "Yards per Carry",
    "receiving_yds": "Receiving Yards",
    "receiving_td": "Receiving TDs",
    "fumbles_fum": "Fumbles",
    "receiving_rec": "Receptions",
    "defensive_solo": "Solo Tackles",
    "defensive_tot": "Total Tackles",
    "defensive_tfl": "Tackles for Loss",
    "interceptions_int": "Interceptions",
    "interceptions_yds": "Interception Yards",
    "interceptions_avg": "Average Int Yards",
    "interceptions_td": "Pick Sixes",
    "defensive_pd": "Pass Deflections",
    "defensive_td": "Total Defensive TDs",
    "defensive_sacks": "Sacks",
    "defensive_qb_hur": "QB Hurries",
    "receiving_ypc": "Yards Per Catch",
    "epa_per_rec": "EPA/Reception",
    "targets": "Targets",
    "catch_rate": "Catch Rate",
    "rec_targets": "Rec/Targets",
    "receiving_ypr": "YPC",
    "40 Yard": "40-Yard Dash",
    "10-Yard Split": "10-Yard Split",
    "3Cone": "3-Cone Drill",
    "punting_tb":"Touchbacks",
    "punting_no":"Punts",
    "punting_yds":"Punting Yards",
    "punting_ypp":"Yards per Punt",
    "punting_in_20":"Punts inside the 20"
}

FILTERED_STATS_PATH = "data/filtered_player_stats_full.csv"
COMBINE_STATS_PATH = "data/combine_pro_day.csv"
LOGO_PATH = "assets/images/logo.png"
